name: CI

on: 
  push:
    branches:    
      - master 

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 14.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        HEROKU_APP_NAME:  ${{ secrets.HEROKU_APP_NAME }}
        HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
    
    - name: yarn install
      run: |
        yarn install
    - name: yarn test
      run: |
        yarn test 
      env:
        CI: true
      
    - name: yarn build
      run: |
        yarn run build --if-present

    - name: Add remote origin
      run: |
        git remote add heroku https://heroku:84300075-76f4-4a4c-8570-34c7c9996886@git.heroku.com/github-init-ci.git
    - name: Deploy to Heroku
      run: |
        git push heroku HEAD:master -f